<?php

use Drupal\Core\URL;
/**
 * @param $existing
 * @param $type
 * @param $theme
 * @param $path
 * @return array
 */
function bb_theme($existing, $type, $theme, $path) {
  return [
    'store_locator' => [
      'variables' => [
        'items' => [],
      ],
    ],
    'store_locator_results' => [
      'variables' => [
        'items' => [],
      ],
    ],
  ];
}

/**
 * Implements hook_preprocess_html().
 * @param $variables
 */
function bb_preprocess_html(&$variables) {
  /* Attach library to Store Locator. */
  $url = Url::fromRoute('<current>')->toString();
  if ($url == '/store-locator') {
    $variables['#attached']['library'][] = 'bb/store-locator';
  }
  if ($url == '/store-locator-results') {
    $variables['#attached']['library'][] = 'bb/store-locator-results';
  }
}
