<?php

use Drupal\Core\URL;
/**
 * @param $existing
 * @param $type
 * @param $theme
 * @param $path
 * @return array
 */
function bb_theme($existing, $type, $theme, $path) {
  return [
    'store_locator' => [
      'variables' => [
        'items' => [],
        '#attached' => [
          'library' => ['bb/store-locator']
        ],
      ],
    ],
    'store_locator_results' => [
      'variables' => [
        'items' => [],
        '#attached' => [
          'library' => ['bb/store-locator-results']
        ],
      ],
    ],
  ];
}
